# Generated by Django 3.2.3 on 2021-05-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Сервис')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('comments', models.TextField(verbose_name='Коментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата объявления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('photo_file', models.FileField(blank=True, null=True, upload_to='photo_file/', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
