# Generated by Django 3.2.3 on 2021-05-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='file',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='document_file/', verbose_name='Файл'),
        ),
    ]
